package minestrapteam.mcore.lib;

import cpw.mods.fml.common.registry.GameRegistry;
import clashsoft.cslib.minecraft.block.CSBlocks;
import minestrapteam.mcore.block.MCBlockCustom2;
import minestrapteam.mcore.block.MCBlockStairs;
import minestrapteam.mcore.block.MCBlockStonecutter;
import minestrapteam.mcore.util.MCAssetManager;
import minestrapteam.mcore.util.MCBlockHelper;
import minestrapteam.minestrappolation.Minestrappolation;
import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;

public class MCBlocks
{
	public static Block	stoneCutter;
	
	public static Block	stone;
	public static Block stoneStairsRaw;
	public static Block stoneStairsTiles;
	public static Block	stone2;
	public static Block	stoneTin;
	public static Block stoneTinStairsRaw;
	public static Block stoneTinStairsBricks;
	public static Block stoneTinStairsTiles;
	public static Block stoneTinStairsCracked;
	public static Block	stoneTin2;
	public static Block	stoneBronze;
	public static Block stoneBronzeStairsRaw;
	public static Block stoneBronzeStairsBricks;
	public static Block stoneBronzeStairsTiles;
	public static Block stoneBronzeStairsCracked;
	public static Block	stoneBronze2;
	public static Block	stoneSteel;
	public static Block stoneSteelStairsRaw;
	public static Block stoneSteelStairsBricks;
	public static Block stoneSteelStairsTiles;
	public static Block stoneSteelStairsCracked;
	public static Block	stoneSteel2;
	public static Block	stoneMeurodite;
	public static Block stoneMeuroditeStairsRaw;
	public static Block stoneMeuroditeStairsBricks;
	public static Block stoneMeuroditeStairsTiles;
	public static Block stoneMeuroditeStairsCracked;
	public static Block	stoneMeurodite2;
	
	public static Block	graniteSlate;
	public static Block graniteSlateStairsRaw;
	public static Block graniteSlateStairsBricks;
	public static Block graniteSlateStairsTiles;
	public static Block	graniteSlate2;
	public static Block	graniteSlateTin;
	public static Block graniteSlateTinStairsRaw;
	public static Block graniteSlateTinStairsBricks;
	public static Block graniteSlateTinStairsTiles;
	public static Block	graniteSlateTin2;
	public static Block	graniteSlateBronze;
	public static Block graniteSlateBronzeStairsRaw;
	public static Block graniteSlateBronzeStairsBricks;
	public static Block graniteSlateBronzeStairsTiles;
	public static Block	graniteSlateBronze2;
	public static Block	graniteSlateSteel;
	public static Block graniteSlateSteelStairsRaw;
	public static Block graniteSlateSteelStairsBricks;
	public static Block graniteSlateSteelStairsTiles;
	public static Block	graniteSlateSteel2;
	public static Block	graniteSlateMeurodite;
	public static Block graniteSlateMeuroditeStairsRaw;
	public static Block graniteSlateMeuroditeStairsBricks;
	public static Block graniteSlateMeuroditeStairsTiles;
	public static Block	graniteSlateMeurodite2;
	
	public static Block	sandstone;
	public static Block sandstoneStairsBricks;
	public static Block sandstoneStairsTiles;
	public static Block	sandstone2;
	public static Block	redSandstone;
	public static Block redSandstoneStairsRaw;
	public static Block redSandstoneStairsBricks;
	public static Block redSandstoneStairsTiles;
	public static Block	redSandstone2;
	public static Block	flint;
	public static Block flintStairsRaw;
	public static Block flintStairsBricks;
	public static Block flintStairsTiles;
	public static Block	flint2;
	public static Block	lapis;
	public static Block lapisStairsRaw;
	public static Block lapisStairsBricks;
	public static Block lapisStairsTiles;
	public static Block	lapis2;
	public static Block	obsidian;
	public static Block obsidianStairsRaw;
	public static Block obsidianStairsBricks;
	public static Block obsidianStairsTiles;
	public static Block	obsidian2;
	public static Block	endstone;
	public static Block endstoneStairsRaw;
	public static Block endstoneStairsBricks;
	public static Block endstoneStairsTiles;
	public static Block endstoneStairsCracked;
	public static Block	endstone2;
	public static Block	bedrock;
	public static Block bedrockStairsRaw;
	public static Block bedrockStairsBricks;
	public static Block bedrockStairsTiles;
	public static Block	bedrock2;
	public static Block	netherrack;
	public static Block netherrackStairsRaw;
	public static Block netherrackStairsTiles;
	public static Block	netherrack2;
	public static Block	netherQuartz;
	public static Block netherQuartzStairsBricks;
	public static Block netherQuartzStairsTiles;
	public static Block	netherQuartz2;
	public static Block	desertQuartz;
	public static Block desertQuartzStairsRaw;
	public static Block desertQuartzStairsBricks;
	public static Block desertQuartzStairsTiles;
	public static Block	desertQuartz2;
	public static Block	radiantQuartz;
	public static Block radiantQuartzStairsRaw;
	public static Block radiantQuartzStairsBricks;
	public static Block radiantQuartzStairsTiles;
	public static Block	radiantQuartz2;
	
	public static Block	clay;
	public static Block clayStairsRaw;
	public static Block clayStairsTiles;
	public static Block	clay2;
	public static Block	blackClay;
	public static Block blackClayStairsRaw;
	public static Block blackClayStairsBricks;
	public static Block blackClayStairsTiles;
	public static Block	blackClay2;
	public static Block	blueClay;
	public static Block blueClayStairsRaw;
	public static Block blueClayStairsBricks;
	public static Block blueClayStairsTiles;
	public static Block	blueClay2;
	public static Block	brownClay;
	public static Block brownClayStairsRaw;
	public static Block brownClayStairsBricks;
	public static Block brownClayStairsTiles;
	public static Block	brownClay2;
	public static Block	cyanClay;
	public static Block cyanClayStairsRaw;
	public static Block cyanClayStairsBricks;
	public static Block cyanClayStairsTiles;
	public static Block	cyanClay2;
	public static Block	lightBlueClay;
	public static Block lightBlueClayStairsRaw;
	public static Block lightBlueClayStairsBricks;
	public static Block lightBlueClayStairsTiles;
	public static Block	lightBlueClay2;
	public static Block	limeClay;
	public static Block limeClayStairsRaw;
	public static Block limeClayStairsBricks;
	public static Block limeClayStairsTiles;
	public static Block	limeClay2;
	public static Block	magentaClay;
	public static Block magentaClayStairsRaw;
	public static Block magentaClayStairsBricks;
	public static Block magentaClayStairsTiles;
	public static Block	magentaClay2;
	public static Block	orangeClay;
	public static Block orangeClayStairsRaw;
	public static Block orangeClayStairsBricks;
	public static Block orangeClayStairsTiles;
	public static Block	orangeClay2;
	public static Block	pinkClay;
	public static Block pinkClayStairsRaw;
	public static Block pinkClayStairsBricks;
	public static Block pinkClayStairsTiles;
	public static Block	pinkClay2;
	public static Block	purpleClay;
	public static Block purpleClayStairsRaw;
	public static Block purpleClayStairsBricks;
	public static Block purpleClayStairsTiles;
	public static Block	purpleClay2;
	public static Block	redClay;
	public static Block redClayStairsRaw;
	public static Block redClayStairsBricks;
	public static Block redClayStairsTiles;
	public static Block	redClay2;
	public static Block	silverClay;
	public static Block silverClayStairsRaw;
	public static Block silverClayStairsBricks;
	public static Block silverClayStairsTiles;
	public static Block	silverClay2;
	public static Block	whiteClay;
	public static Block whiteClayStairsRaw;
	public static Block whiteClayStairsBricks;
	public static Block whiteClayStairsTiles;
	public static Block	whiteClay2;
	public static Block	yellowClay;
	public static Block yellowClayStairsRaw;
	public static Block yellowClayStairsBricks;
	public static Block yellowClayStairsTiles;
	public static Block	yellowClay2;
	public static Block greenClay;
	public static Block greenClayStairsRaw;
	public static Block greenClayStairsBricks;
	public static Block greenClayStairsTiles;
	public static Block greenClay2;
	public static Block greyClay;
	public static Block greyClayStairsRaw;
	public static Block greyClayStairsBricks;
	public static Block greyClayStairsTiles;
	public static Block greyClay2;
	
	public static Block	woodOak;
	public static Block woodOakStairsBoards;
	public static Block	woodOak2;
	public static Block	woodBirch;
	public static Block woodBirchStairsBoards;
	public static Block	woodBirch2;
	public static Block	woodSpruce;
	public static Block woodSpruceStairsBoards;
	public static Block	woodSpruce2;
	public static Block	woodJungle;
	public static Block woodJungleStairsBoards;
	public static Block	woodJungle2;
	public static Block woodAcacia;
	public static Block woodAcaciaStairsBoards;
	public static Block woodAcacia2;
	public static Block woodDarkOak;
	public static Block woodDarkOakStairsBoards;
	public static Block woodDarkOak2;
	
	public static void init()
	{
		stoneCutter = new MCBlockStonecutter().setCreativeTab(Minestrappolation.tabTech).setBlockTextureName(MCAssetManager.getMachineTexture("stonecutter")).setHardness(3.5F).setStepSound(Block.soundTypeStone);
		CSBlocks.addBlock(stoneCutter, "stonecutter");
		
		CreativeTabs tab = Minestrappolation.tabStoneDecor;
		CreativeTabs tab_decor = Minestrappolation.tabDecorationBlocks;
		
		String[] types_stone = new String[] { null, null, "pattern_bricks", "tiles", "road", "refined", null, null, null, null, null, null, null, null, "lamp_glowstone", "lamp_sunstone" };
		String[] types_stone_2 = new String[] { "pillar", null, null, "tile_slab", "refined_slab" };
		String[] types_granite = new String[] { "raw", "bricks", "pattern_bricks", "tiles", "road", "refined", "chiseled" };
		String[] types_sandstone = new String[] { null, "bricks", "pattern_bricks", "tiles", "road", null, "chiseled", "chiseled_2", "mossy" };
		String[] types_sandstone_2 = new String[] { "pillar", null, "brick_slab", "tile_slab", "refined_slab" };
		String[] types_redsandstone = new String[] { "raw", "bricks", "pattern_bricks", "tiles", "road", "refined", "chiseled", "chiseled_2", "chiseled_3", "mossy" };
		String[] types_redsandstone_2 = new String[] { "pillar", "raw_slab", "brick_slab", "tile_slab", "refined_slab" };
		String[] types_flint = new String[] { "raw", "bricks", "pattern_bricks", "tiles", "road", "refined", "chiseled", null, null, null, null, null, null, null, "lamp_glowstone", "lamp_sunstone" };
		String[] types_lapis = new String[] { null, "bricks", "pattern_bricks", "tiles", "road", "refined", "chiseled", "gilded" };
		String[] types_obsidian = new String[] { null, "bricks", "pattern_bricks", "tiles", "road", "refined", "chiseled", "godstone_lamp" };
		String[] types_endstone = new String[] { "raw", "bricks", "pattern_bricks", "tiles", "road", "refined", "chiseled" };
		String[] types_bedrock = new String[] { null, "bricks", "pattern_bricks", "tiles", "road", "refined", "chiseled", null, null, null, null, null, null, null, "lamp_glowstone", "lamp_sunstone" };
		String[] types_netherrack = new String[] { null, null, "pattern_bricks", "tiles", "road", "refined", "chiseled" };
		String[] types_netherrack2 = new String[] { "pillar", "raw_slab", null, "tile_slab", "refined_slab" };
		String[] types_netherquartz = new String[] { null, "bricks", "pattern_bricks", "tiles", "road", "refined", "chiseled" };
		String[] types_netherquartz_2 = new String[] { "pillar", null, "brick_slab", "tile_slab", "refined_slab" };
		String[] types_desertquartz = new String[] { "raw", "bricks", "pattern_bricks", "tiles", "refined_tiles", "rough_tiles", "road", "refined", "chiseled" };
		String[] types_desertquartz_2 = new String[] { "pillar", "raw_slab", "brick_slab", "tile_slab", "refined_slab" };
		String[] types_radiantquartz = new String[] { "raw", "bricks", "pattern_bricks", "tiles", "road", "refined", "chiseled" };
		String[] types_radiantquartz_2 = new String[] { "pillar", "raw_slab", "brick_slab", "tile_slab", "refined_slab" };
		String[] types_clay = new String[] { null, null, "pattern_bricks", "tiles", "road", "refined", "chiseled" };
		String[] types_clay_2 = new String[] { "pillar", "raw_slab", null, "tile_slab", "refined_slab" };
		String[] types_colored_clay = new String[] { null, "bricks", "pattern_bricks", "tiles", "road", "refined", "chiseled" };
		String[] types_colored_clay_2 = new String[] { "pillar", "raw_slab", "brick_slab", "tile_slab", "refined_slab" };
		
		stone = MCBlockHelper.createStoneBlock(types_stone, "stone", 1.5F, 10.0F, 0, tab).setIsStone();
		stone2 = MCBlockHelper.createStoneBlock2(types_stone_2, "stone", 1.5F, 10.0F, 0, tab);
		stoneStairsRaw = new MCBlockStairs(Blocks.stone, 0).setBlockName("stairs_stone_raw").setCreativeTab(tab);
		CSBlocks.addBlock(stoneStairsRaw);
		stoneStairsTiles = new MCBlockStairs(stone, 3).setBlockName("stairs_stone_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(stoneStairsTiles);
		stoneTin = MCBlockHelper.createStoneBlock("stone_tin", 1.7F, 11.0F, 0, tab).setIsStone();
		stoneTin2 = MCBlockHelper.createStoneBlock2("stone_tin", 1.7F, 11.0F, 0, tab);
		stoneTinStairsRaw = new MCBlockStairs(stoneTin, 0).setBlockName("stairs_stone_tin_raw").setCreativeTab(tab);
		CSBlocks.addBlock(stoneTinStairsRaw);
		stoneTinStairsBricks = new MCBlockStairs(stoneTin, 1).setBlockName("stairs_stone_tin_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(stoneTinStairsBricks);
		stoneTinStairsTiles = new MCBlockStairs(stoneTin, 3).setBlockName("stairs_stone_tin_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(stoneTinStairsTiles);
		stoneTinStairsCracked = new MCBlockStairs(stoneTin, 7).setBlockName("stairs_stone_tin_cracked").setCreativeTab(tab);
		CSBlocks.addBlock(stoneTinStairsCracked);
		stoneBronze = MCBlockHelper.createStoneBlock("stone_bronze", 1.7F, 20.0F, 0, tab).setIsStone();
		stoneBronze2 = MCBlockHelper.createStoneBlock2("stone_bronze", 1.7F, 20.0F, 0, tab);
		stoneBronzeStairsRaw = new MCBlockStairs(stoneBronze, 0).setBlockName("stairs_stone_bronze_raw").setCreativeTab(tab);
		CSBlocks.addBlock(stoneBronzeStairsRaw);
		stoneBronzeStairsBricks = new MCBlockStairs(stoneBronze, 1).setBlockName("stairs_stone_bronze_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(stoneBronzeStairsBricks);
		stoneBronzeStairsTiles = new MCBlockStairs(stoneBronze, 3).setBlockName("stairs_stone_bronze_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(stoneBronzeStairsTiles);
		stoneBronzeStairsCracked = new MCBlockStairs(stoneBronze, 7).setBlockName("stairs_stone_bronze_cracked").setCreativeTab(tab);
		CSBlocks.addBlock(stoneBronzeStairsCracked);
		stoneSteel = MCBlockHelper.createStoneBlock("stone_steel", 3F, 11.0F, 0, tab).setIsStone();
		stoneSteel2 = MCBlockHelper.createStoneBlock2("stone_steel", 3F, 11.0F, 0, tab);
		stoneSteelStairsRaw = new MCBlockStairs(stoneSteel, 0).setBlockName("stairs_stone_steel_raw").setCreativeTab(tab);
		CSBlocks.addBlock(stoneSteelStairsRaw);
		stoneSteelStairsBricks = new MCBlockStairs(stoneSteel, 1).setBlockName("stairs_stone_steel_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(stoneSteelStairsBricks);
		stoneSteelStairsTiles = new MCBlockStairs(stoneSteel, 3).setBlockName("stairs_stone_steel_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(stoneSteelStairsTiles);
		stoneSteelStairsCracked = new MCBlockStairs(stoneSteel, 7).setBlockName("stairs_stone_steel_cracked").setCreativeTab(tab);
		CSBlocks.addBlock(stoneSteelStairsCracked);
		stoneMeurodite = MCBlockHelper.createStoneBlock("stone_meurodite", 2.3F, 15.0F, 0, tab).setIsStone();
		stoneMeurodite2 = MCBlockHelper.createStoneBlock2("stone_meurodite", 2.3F, 15.0F, 0, tab);
		stoneMeuroditeStairsRaw = new MCBlockStairs(stoneMeurodite, 0).setBlockName("stairs_meurodite_raw").setCreativeTab(tab);
		CSBlocks.addBlock(stoneMeuroditeStairsRaw);
		stoneMeuroditeStairsBricks = new MCBlockStairs(stoneMeurodite, 1).setBlockName("stairs_meurodite_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(stoneMeuroditeStairsBricks);
		stoneMeuroditeStairsTiles = new MCBlockStairs(stoneMeurodite, 3).setBlockName("stairs_meurodite_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(stoneMeuroditeStairsTiles);
		stoneMeuroditeStairsCracked = new MCBlockStairs(stoneMeurodite, 7).setBlockName("stairs_meurodite_cracked").setCreativeTab(tab);
		CSBlocks.addBlock(stoneMeuroditeStairsCracked);
		
		graniteSlate = MCBlockHelper.createStoneBlock(types_granite, "granite", 2F, 15.0F, 0, tab);
		graniteSlate2 = MCBlockHelper.createStoneBlock2("granite", 2F, 15.0F, 0, tab);
		graniteSlateStairsRaw = new MCBlockStairs(graniteSlate, 0).setBlockName("stairs_granite_slate_raw").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateStairsRaw);
		graniteSlateStairsBricks = new MCBlockStairs(graniteSlate, 1).setBlockName("stairs_granite_slate_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateStairsBricks);
		graniteSlateStairsTiles = new MCBlockStairs(graniteSlate, 3).setBlockName("stairs_granite_slate_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateStairsTiles);
		graniteSlateTin = MCBlockHelper.createStoneBlock(types_granite, "granite_tin", 2.2F, 16.0F, 0, tab);
		graniteSlateTin2 = MCBlockHelper.createStoneBlock2("granite_tin", 2.2F, 16.0F, 0, tab);
		graniteSlateTinStairsRaw = new MCBlockStairs(graniteSlateTin, 0).setBlockName("stairs_granite_slate_tin_raw").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateTinStairsRaw);
		graniteSlateTinStairsBricks = new MCBlockStairs(graniteSlateTin, 1).setBlockName("stairs_granite_slate_tin_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateTinStairsBricks);
		graniteSlateTinStairsTiles = new MCBlockStairs(graniteSlateTin, 3).setBlockName("stairs_granite_slate_tin_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateTinStairsTiles);
		graniteSlateBronze = MCBlockHelper.createStoneBlock(types_granite, "granite_bronze", 2.2F, 30.0F, 0, tab);
		graniteSlateBronze2 = MCBlockHelper.createStoneBlock2("granite_bronze", 2.2F, 30.0F, 0, tab);
		graniteSlateBronzeStairsRaw = new MCBlockStairs(graniteSlateBronze, 0).setBlockName("stairs_granite_slate_bronze_raw").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateBronzeStairsRaw);
		graniteSlateBronzeStairsBricks = new MCBlockStairs(graniteSlateBronze, 1).setBlockName("stairs_granite_slate_bronze_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateBronzeStairsBricks);
		graniteSlateBronzeStairsTiles = new MCBlockStairs(graniteSlateBronze, 3).setBlockName("stairs_granite_slate_bronze_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateBronzeStairsTiles);
		graniteSlateSteel = MCBlockHelper.createStoneBlock(types_granite, "granite_steel", 4F, 16.0F, 0, tab);
		graniteSlateSteel2 = MCBlockHelper.createStoneBlock2("granite_steel", 4F, 16.0F, 0, tab);
		graniteSlateSteelStairsRaw = new MCBlockStairs(graniteSlateSteel, 0).setBlockName("stairs_granite_slate_steel_raw").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateSteelStairsRaw);
		graniteSlateSteelStairsBricks = new MCBlockStairs(graniteSlateSteel, 1).setBlockName("stairs_granite_slate_steel_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateSteelStairsBricks);
		graniteSlateSteelStairsTiles = new MCBlockStairs(graniteSlateSteel, 3).setBlockName("stairs_granite_slate_steel_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateSteelStairsTiles);
		graniteSlateMeurodite = MCBlockHelper.createStoneBlock(types_granite, "granite_meurodite", 3F, 22.5F, 0, tab);
		graniteSlateMeurodite2 = MCBlockHelper.createStoneBlock2("granite_meurodite", 3F, 22.5F, 0, tab);
		graniteSlateMeuroditeStairsRaw = new MCBlockStairs(graniteSlateMeurodite, 0).setBlockName("stairs_granite_slate_meurodite_raw").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateMeuroditeStairsRaw);
		graniteSlateMeuroditeStairsBricks = new MCBlockStairs(graniteSlateMeurodite, 1).setBlockName("stairs_granite_slate_meurodite_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateMeuroditeStairsBricks);
		graniteSlateMeuroditeStairsTiles = new MCBlockStairs(graniteSlateMeurodite, 3).setBlockName("stairs_granite_slate_meurodite_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(graniteSlateMeuroditeStairsTiles);
		
		sandstone = MCBlockHelper.createStoneBlock(types_sandstone, "sandstone", 0.8F, 1.33F, 0, tab);
		sandstone2 = MCBlockHelper.createStoneBlock2(types_sandstone_2, "sandstone", 0.8F, 1.33F, 0, tab);
		sandstoneStairsBricks = new MCBlockStairs(sandstone, 1).setBlockName("stairs_sandstone_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(sandstoneStairsBricks);
		sandstoneStairsTiles = new MCBlockStairs(sandstone, 3).setBlockName("stairs_sandstone_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(sandstoneStairsTiles);
		redSandstone = MCBlockHelper.createStoneBlock(types_redsandstone, "red_sandstone", 0.8F, 1.33F, 0, tab).setIsRedSandstone();
		redSandstone2 = MCBlockHelper.createStoneBlock2(types_redsandstone_2, "red_sandstone", 0.8F, 1.33F, 0, tab).setIsRedSandstone();
		redSandstoneStairsRaw = new MCBlockStairs(redSandstone, 0).setBlockName("stairs_red_sandstone_raw").setCreativeTab(tab);
		CSBlocks.addBlock(redSandstoneStairsRaw);
		redSandstoneStairsBricks = new MCBlockStairs(redSandstone, 1).setBlockName("stairs_red_sandstone_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(redSandstoneStairsBricks);
		redSandstoneStairsTiles = new MCBlockStairs(redSandstone, 3).setBlockName("stairs_red_sandstone_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(redSandstoneStairsTiles);
		flint = MCBlockHelper.createStoneBlock(types_flint, "flint", 1.8F, 15.0F, 1, tab);
		flint2 = MCBlockHelper.createStoneBlock2("flint", 1.8F, 15.0F, 1, tab);
		flintStairsRaw = new MCBlockStairs(flint, 0).setBlockName("stairs_flint_raw").setCreativeTab(tab);
		CSBlocks.addBlock(flintStairsRaw);
		flintStairsBricks = new MCBlockStairs(flint, 1).setBlockName("stairs_flint_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(flintStairsBricks);
		flintStairsTiles = new MCBlockStairs(flint, 3).setBlockName("stairs_flint_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(flintStairsTiles);
		lapis = MCBlockHelper.createStoneBlock(types_lapis, "lapis", 3.0F, 5.0F, 1, tab).setChiseledSided();
		lapis2 = MCBlockHelper.createStoneBlock2("lapis", 3.0F, 5.0F, 1, tab);
		lapisStairsRaw = new MCBlockStairs(Blocks.lapis_block, 0).setBlockName("stairs_lapis_raw").setCreativeTab(tab);
		CSBlocks.addBlock(lapisStairsRaw);
		lapisStairsBricks = new MCBlockStairs(lapis, 1).setBlockName("stairs_lapis_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(lapisStairsBricks);
		lapisStairsTiles = new MCBlockStairs(lapis, 3).setBlockName("stairs_lapis_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(lapisStairsTiles);
		obsidian = MCBlockHelper.createStoneBlock(types_obsidian, "obsidian", 50.0F, 2000.0F, 3, tab).setEnderDragonCantDestroy();
		obsidian2 = MCBlockHelper.createStoneBlock2("obsidian", 50.0F, 2000.0F, 3, tab).setEnderDragonCantDestroy();
		obsidianStairsRaw = new MCBlockStairs(Blocks.obsidian, 0).setBlockName("stairs_obsidian_raw").setCreativeTab(tab);
		CSBlocks.addBlock(obsidianStairsRaw);
		obsidianStairsBricks = new MCBlockStairs(obsidian, 1).setBlockName("stairs_obsidian_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(obsidianStairsBricks);
		obsidianStairsTiles = new MCBlockStairs(obsidian, 3).setBlockName("stairs_obsidian_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(obsidianStairsTiles);
		endstone = MCBlockHelper.createStoneBlock(types_endstone, "endstone", 3.0F, 15.0F, 0, tab).setChiseledSided().setEnderDragonCantDestroy();
		endstone2 = MCBlockHelper.createStoneBlock2("endstone", 3.0F, 15.0F, 0, tab).setEnderDragonCantDestroy();
		endstoneStairsRaw = new MCBlockStairs(endstone, 0).setBlockName("stairs_endstone_raw").setCreativeTab(tab);
		CSBlocks.addBlock(endstoneStairsRaw);
		endstoneStairsBricks = new MCBlockStairs(endstone, 1).setBlockName("stairs_endstone_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(endstoneStairsBricks);
		endstoneStairsTiles = new MCBlockStairs(endstone, 3).setBlockName("stairs_endstone_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(endstoneStairsTiles);
		endstoneStairsCracked = new MCBlockStairs(Blocks.end_stone, 0).setBlockName("stairs_endstone_cracked").setCreativeTab(tab);
		CSBlocks.addBlock(endstoneStairsCracked);
		bedrock = MCBlockHelper.createStoneBlock(types_bedrock, "bedrock", 80F, 6000000.0F, 4, tab).setRoadWalkSpeed(1.5F).setEnderDragonCantDestroy();
		bedrock2 = MCBlockHelper.createStoneBlock2("bedrock", 80F, 6000000.0F, 4, tab).setEnderDragonCantDestroy();
		bedrockStairsRaw = new MCBlockStairs(Blocks.bedrock, 0).setBlockName("stairs_bedrock_raw").setCreativeTab(tab);
		CSBlocks.addBlock(bedrockStairsRaw);
		bedrockStairsBricks = new MCBlockStairs(bedrock, 1).setBlockName("stairs_bedrock_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(bedrockStairsBricks);
		bedrockStairsTiles = new MCBlockStairs(bedrock, 3).setBlockName("stairs_bedrock_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(bedrockStairsTiles);
		netherrack = MCBlockHelper.createStoneBlock(types_netherrack, "netherrack", 0.4F, 0.67F, 0, tab).setIsNetherrack();
		netherrack2 = MCBlockHelper.createStoneBlock2(types_netherrack2, "netherrack", 0.4F, 0.67F, 0, tab).setIsNetherrack();
		netherrackStairsRaw = new MCBlockStairs(Blocks.netherrack, 0).setBlockName("stairs_netherrack_raw").setCreativeTab(tab);
		CSBlocks.addBlock(netherrackStairsRaw);
		netherrackStairsTiles = new MCBlockStairs(netherrack, 3).setBlockName("stairs_netherrack_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(netherrackStairsTiles);
		netherQuartz = MCBlockHelper.createStoneBlock(types_netherquartz, "netherquartz", 0.8F, 1.33F, 0, tab).setChiseledSided();
		netherQuartz2 = MCBlockHelper.createStoneBlock2(types_netherquartz_2, "netherquartz", 0.8F, 1.33F, 0, tab);
		netherQuartzStairsBricks = new MCBlockStairs(netherQuartz, 1).setBlockName("stairs_nether_quartz_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(netherQuartzStairsBricks);
		netherQuartzStairsTiles = new MCBlockStairs(netherQuartz, 3).setBlockName("stairs_nether_quartz_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(netherQuartzStairsTiles);
		desertQuartz = MCBlockHelper.createStoneBlock(types_desertquartz, "desertquartz", 1.7F, 4.0F, 1, tab).setChiseledSided();
		desertQuartz2 = MCBlockHelper.createStoneBlock2(types_desertquartz_2, "desertquartz", 1.7F, 4.0F, 1, tab);
		desertQuartzStairsRaw = new MCBlockStairs(desertQuartz, 0).setBlockName("stairs_desert_quartz_raw").setCreativeTab(tab);
		CSBlocks.addBlock(desertQuartzStairsRaw);
		desertQuartzStairsBricks = new MCBlockStairs(desertQuartz, 1).setBlockName("stairs_desert_quartz_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(desertQuartzStairsBricks);
		desertQuartzStairsTiles = new MCBlockStairs(desertQuartz, 3).setBlockName("stairs_desert_quartz_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(desertQuartzStairsTiles);
		radiantQuartz = MCBlockHelper.createStoneBlock(types_radiantquartz, "radiant_quartz", 2F, 6.0F, 3, tab).setBeaconBase().setLightLevel(0.5F);
		radiantQuartz2 = ((MCBlockCustom2) MCBlockHelper.createStoneBlock2(types_radiantquartz_2, "radiant_quartz", 2F, 6.0F, 3, tab).setBeaconBase().setLightLevel(0.5F)).setIsRadiantQuartz();
		radiantQuartzStairsRaw = new MCBlockStairs(radiantQuartz, 0).setBlockName("stairs_radiant_quartz_raw").setCreativeTab(tab);
		CSBlocks.addBlock(radiantQuartzStairsRaw);
		radiantQuartzStairsBricks = new MCBlockStairs(radiantQuartz, 1).setBlockName("stairs_radiant_quartz_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(radiantQuartzStairsBricks);
		radiantQuartzStairsTiles = new MCBlockStairs(radiantQuartz, 3).setBlockName("stairs_radiant_quartz_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(radiantQuartzStairsTiles);
		
		clay = MCBlockHelper.createStoneBlock(types_clay, "clay", 1.25F, 7.0F, 0, tab).setIsClay();
		clay2 = MCBlockHelper.createStoneBlock2(types_clay_2, "clay", 1.25F, 7.0F, 0, tab);
		clayStairsRaw = new MCBlockStairs(Blocks.hardened_clay, 0).setBlockName("stairs_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(clayStairsRaw);
		clayStairsTiles = new MCBlockStairs(clay, 3).setBlockName("stairs_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(clayStairsTiles);
		blackClay = MCBlockHelper.createStoneBlock(types_colored_clay, "black_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		blackClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "black_clay", 1.25F, 7.0F, 0, tab);
		blackClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 15).setBlockName("stairs_black_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(blackClayStairsRaw);
		blackClayStairsBricks = new MCBlockStairs(blackClay, 1).setBlockName("stairs_black_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(blackClayStairsBricks);
		blackClayStairsTiles = new MCBlockStairs(blackClay, 3).setBlockName("stairs_black_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(blackClayStairsTiles);
		blueClay = MCBlockHelper.createStoneBlock(types_colored_clay, "blue_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		blueClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "blue_clay", 1.25F, 7.0F, 0, tab);
		blueClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 11).setBlockName("stairs_blue_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(blueClayStairsRaw);
		blueClayStairsBricks = new MCBlockStairs(blueClay, 1).setBlockName("stairs_blue_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(blueClayStairsBricks);
		blueClayStairsTiles = new MCBlockStairs(blueClay, 3).setBlockName("stairs_blue_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(blueClayStairsTiles);
		brownClay = MCBlockHelper.createStoneBlock(types_colored_clay, "brown_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		brownClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "brown_clay", 1.25F, 7.0F, 0, tab);
		brownClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 12).setBlockName("stairs_brown_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(brownClayStairsRaw);
		brownClayStairsBricks = new MCBlockStairs(brownClay, 1).setBlockName("stairs_brown_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(brownClayStairsBricks);
		brownClayStairsTiles = new MCBlockStairs(brownClay, 3).setBlockName("stairs_brown_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(brownClayStairsTiles);
		cyanClay = MCBlockHelper.createStoneBlock(types_colored_clay, "cyan_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		cyanClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "cyan_clay", 1.25F, 7.0F, 0, tab);
		cyanClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 9).setBlockName("stairs_cyan_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(cyanClayStairsRaw);
		cyanClayStairsBricks = new MCBlockStairs(cyanClay, 1).setBlockName("stairs_cyan_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(cyanClayStairsBricks);
		cyanClayStairsTiles = new MCBlockStairs(cyanClay, 3).setBlockName("stairs_cyan_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(cyanClayStairsTiles);
		lightBlueClay = MCBlockHelper.createStoneBlock(types_colored_clay, "lightblue_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		lightBlueClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "lightblue_clay", 1.25F, 7.0F, 0, tab);
		lightBlueClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 3).setBlockName("stairs_light_blue_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(lightBlueClayStairsRaw);
		lightBlueClayStairsBricks = new MCBlockStairs(lightBlueClay, 1).setBlockName("stairs_light_blue_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(lightBlueClayStairsBricks);
		lightBlueClayStairsTiles = new MCBlockStairs(lightBlueClay, 3).setBlockName("stairs_light_blue_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(lightBlueClayStairsTiles);
		limeClay = MCBlockHelper.createStoneBlock(types_colored_clay, "lime_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		limeClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "lime_clay", 1.25F, 7.0F, 0, tab);
		limeClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 5).setBlockName("stairs_lime_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(limeClayStairsRaw);
		limeClayStairsBricks = new MCBlockStairs(limeClay, 1).setBlockName("stairs_lime_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(limeClayStairsBricks);
		limeClayStairsTiles = new MCBlockStairs(limeClay, 3).setBlockName("stairs_lime_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(limeClayStairsTiles);
		magentaClay = MCBlockHelper.createStoneBlock(types_colored_clay, "magenta_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		magentaClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "magenta_clay", 1.25F, 7.0F, 0, tab);
		magentaClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 2).setBlockName("stairs_magenta_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(magentaClayStairsRaw);
		magentaClayStairsBricks = new MCBlockStairs(magentaClay, 1).setBlockName("stairs_magenta_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(magentaClayStairsBricks);
		magentaClayStairsTiles = new MCBlockStairs(magentaClay, 3).setBlockName("stairs_magenta_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(magentaClayStairsTiles);
		orangeClay = MCBlockHelper.createStoneBlock(types_colored_clay, "orange_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		orangeClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "orange_clay", 1.25F, 7.0F, 0, tab);
		orangeClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 1).setBlockName("stairs_orange_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(orangeClayStairsRaw);
		orangeClayStairsBricks = new MCBlockStairs(orangeClay, 1).setBlockName("stairs_orange_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(orangeClayStairsBricks);
		orangeClayStairsTiles = new MCBlockStairs(orangeClay, 3).setBlockName("stairs_orange_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(orangeClayStairsTiles);
		pinkClay = MCBlockHelper.createStoneBlock(types_colored_clay, "pink_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		pinkClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "pink_clay", 1.25F, 7.0F, 0, tab);
		pinkClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 6).setBlockName("stairs_pink_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(pinkClayStairsRaw);
		pinkClayStairsBricks = new MCBlockStairs(pinkClay, 1).setBlockName("stairs_pink_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(pinkClayStairsBricks);
		pinkClayStairsTiles = new MCBlockStairs(pinkClay, 3).setBlockName("stairs_pink_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(pinkClayStairsTiles);
		purpleClay = MCBlockHelper.createStoneBlock(types_colored_clay, "purple_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		purpleClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "purple_clay", 1.25F, 7.0F, 0, tab);
		purpleClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 10).setBlockName("stairs_purple_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(purpleClayStairsRaw);
		purpleClayStairsBricks = new MCBlockStairs(purpleClay, 1).setBlockName("stairs_purple_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(purpleClayStairsBricks);
		purpleClayStairsTiles = new MCBlockStairs(purpleClay, 3).setBlockName("stairs_purple_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(purpleClayStairsTiles);
		redClay = MCBlockHelper.createStoneBlock(types_colored_clay, "red_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		redClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "red_clay", 1.25F, 7.0F, 0, tab);
		redClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 14).setBlockName("stairs_red_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(redClayStairsRaw);
		redClayStairsBricks = new MCBlockStairs(redClay, 1).setBlockName("stairs_red_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(redClayStairsBricks);
		redClayStairsTiles = new MCBlockStairs(redClay, 3).setBlockName("stairs_red_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(redClayStairsTiles);
		silverClay = MCBlockHelper.createStoneBlock(types_colored_clay, "silver_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		silverClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "silver_clay", 1.25F, 7.0F, 0, tab);
		silverClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 8).setBlockName("stairs_silver_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(silverClayStairsRaw);
		silverClayStairsBricks = new MCBlockStairs(silverClay, 1).setBlockName("stairs_silver_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(silverClayStairsBricks);
		silverClayStairsTiles = new MCBlockStairs(silverClay, 3).setBlockName("stairs_silver_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(silverClayStairsTiles);
		whiteClay = MCBlockHelper.createStoneBlock(types_colored_clay, "white_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		whiteClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "white_clay", 1.25F, 7.0F, 0, tab);
		whiteClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 0).setBlockName("stairs_white_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(whiteClayStairsRaw);
		whiteClayStairsBricks = new MCBlockStairs(whiteClay, 1).setBlockName("stairs_white_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(whiteClayStairsBricks);
		whiteClayStairsTiles = new MCBlockStairs(whiteClay, 3).setBlockName("stairs_white_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(whiteClayStairsTiles);
		yellowClay = MCBlockHelper.createStoneBlock(types_colored_clay, "yellow_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		yellowClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "yellow_clay", 1.25F, 7.0F, 0, tab);
		yellowClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 4).setBlockName("stairs_yellow_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(yellowClayStairsRaw);
		yellowClayStairsBricks = new MCBlockStairs(yellowClay, 1).setBlockName("stairs_yellow_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(yellowClayStairsBricks);
		yellowClayStairsTiles = new MCBlockStairs(yellowClay, 3).setBlockName("stairs_yellow_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(yellowClayStairsTiles);
		greenClay = MCBlockHelper.createStoneBlock(types_colored_clay, "green_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		greenClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "green_clay", 1.25F, 7.0F, 0, tab);
		greenClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 13).setBlockName("stairs_green_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(greenClayStairsRaw);
		greenClayStairsBricks = new MCBlockStairs(greenClay, 1).setBlockName("stairs_green_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(greenClayStairsBricks);
		greenClayStairsTiles = new MCBlockStairs(greenClay, 3).setBlockName("stairs_green_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(greenClayStairsTiles);
		greyClay = MCBlockHelper.createStoneBlock(types_colored_clay, "grey_clay", 1.25F, 7.0F, 0, tab).setIsClay();
		greyClay2 = MCBlockHelper.createStoneBlock2(types_colored_clay_2, "grey_clay", 1.25F, 7.0F, 0, tab);
		greyClayStairsRaw = new MCBlockStairs(Blocks.stained_hardened_clay, 7).setBlockName("stairs_grey_clay_raw").setCreativeTab(tab);
		CSBlocks.addBlock(greyClayStairsRaw);
		greyClayStairsBricks = new MCBlockStairs(greyClay, 1).setBlockName("stairs_grey_clay_bricks").setCreativeTab(tab);
		CSBlocks.addBlock(greyClayStairsBricks);
		greyClayStairsTiles = new MCBlockStairs(greyClay, 3).setBlockName("stairs_grey_clay_tiles").setCreativeTab(tab);
		CSBlocks.addBlock(greyClayStairsTiles);
		
		woodOak = MCBlockHelper.createWoodBlock("oak", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodOak2 = MCBlockHelper.createWoodBlock2("oak", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodOakStairsBoards = new MCBlockStairs(woodOak, 1).setBlockName("stairs_wood_oak_raw").setCreativeTab(tab_decor).setStepSound(Block.soundTypeWood);
		CSBlocks.addBlock(woodOakStairsBoards);
		woodBirch = MCBlockHelper.createWoodBlock("birch", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodBirch2 = MCBlockHelper.createWoodBlock2("birch", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodBirchStairsBoards = new MCBlockStairs(woodBirch, 1).setBlockName("stairs_wood_birch_raw").setCreativeTab(tab_decor).setStepSound(Block.soundTypeWood);
		CSBlocks.addBlock(woodBirchStairsBoards);
		woodSpruce = MCBlockHelper.createWoodBlock("spruce", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodSpruce2 = MCBlockHelper.createWoodBlock2("spruce", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodSpruceStairsBoards = new MCBlockStairs(woodSpruce, 1).setBlockName("stairs_wood_spruce_raw").setCreativeTab(tab_decor).setStepSound(Block.soundTypeWood);
		CSBlocks.addBlock(woodSpruceStairsBoards);
		woodJungle = MCBlockHelper.createWoodBlock("jungle", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodJungle2 = MCBlockHelper.createWoodBlock2("jungle", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodJungleStairsBoards = new MCBlockStairs(woodJungle, 1).setBlockName("stairs_wood_jungle_raw").setCreativeTab(tab_decor).setStepSound(Block.soundTypeWood);
		CSBlocks.addBlock(woodJungleStairsBoards);
		woodAcacia = MCBlockHelper.createWoodBlock("acacia", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodAcacia2 = MCBlockHelper.createWoodBlock2("acacia", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodAcaciaStairsBoards = new MCBlockStairs(woodAcacia, 1).setBlockName("stairs_wood_acacia_raw").setCreativeTab(tab_decor).setStepSound(Block.soundTypeWood);
		CSBlocks.addBlock(woodAcaciaStairsBoards);
		woodDarkOak = MCBlockHelper.createWoodBlock("dark_oak", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodDarkOak2 = MCBlockHelper.createWoodBlock2("dark_oak", 2.0F, 5.0F, tab_decor).setStepSound(Block.soundTypeWood);
		woodDarkOakStairsBoards = new MCBlockStairs(woodDarkOak, 1).setBlockName("stairs_wood_dark_oak_raw").setCreativeTab(tab_decor).setStepSound(Block.soundTypeWood);
		CSBlocks.addBlock(woodDarkOakStairsBoards);
	}
}
