package minestrapteam.minestrappolation.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWorkbench extends ModelBase
{
	private ModelRenderer base;
	private ModelRenderer frontSaw1;
	private ModelRenderer frontSaw2;
	private ModelRenderer frontSaw3;
	private ModelRenderer frontSaw4;
	private ModelRenderer frontSaw5;
	private ModelRenderer frontSaw6;
	private ModelRenderer frontHammer1;
	private ModelRenderer frontHammer2;
	private ModelRenderer frontHammer3;
	private ModelRenderer rightSaw1;
	private ModelRenderer rightSaw2;
	private ModelRenderer rightSaw3;
	private ModelRenderer rightSaw4;
	private ModelRenderer rightSaw5;
	private ModelRenderer rightSaw6;
	private ModelRenderer rightHammer1;
	private ModelRenderer rightHammer2;
	private ModelRenderer rightHammer3;
	private ModelRenderer leftCutter1;
	private ModelRenderer leftCutter2;
	private ModelRenderer leftCutter3;
	private ModelRenderer leftCutter4;
	private ModelRenderer leftCutter5;
	private ModelRenderer backCutter1;
	private ModelRenderer backCutter2;
	private ModelRenderer backCutter3;
	private ModelRenderer backCutter4;
	private ModelRenderer backCutter5;

	public ModelWorkbench()
	{
		this.textureWidth = 64;
		this.textureHeight = 32;

		this.base = new ModelRenderer(this, 0, 0);
		this.base.addBox(0F, 0F, 0F, 16, 16, 16);
		this.base.setRotationPoint(-8F, 8F, -8F);
		this.base.setTextureSize(64, 32);
		this.base.mirror = true;
		setRotation(this.base, 0F, 0F, 0F);
		this.frontSaw1 = new ModelRenderer(this, 48, 0);
		this.frontSaw1.addBox(0F, 0F, 0F, 3, 1, 1);
		this.frontSaw1.setRotationPoint(3F, 11F, -9F);
		this.frontSaw1.setTextureSize(64, 32);
		this.frontSaw1.mirror = true;
		setRotation(this.frontSaw1, 0F, 0F, 0F);
		this.frontSaw2 = new ModelRenderer(this, 56, 0);
		this.frontSaw2.addBox(0F, 0F, 0F, 1, 1, 1);
		this.frontSaw2.setRotationPoint(3F, 12F, -9F);
		this.frontSaw2.setTextureSize(64, 32);
		this.frontSaw2.mirror = true;
		setRotation(this.frontSaw2, 0F, 0F, 0F);
		this.frontSaw3 = new ModelRenderer(this, 60, 0);
		this.frontSaw3.addBox(0F, 0F, 0F, 1, 1, 1);
		this.frontSaw3.setRotationPoint(5F, 12F, -9F);
		this.frontSaw3.setTextureSize(64, 32);
		this.frontSaw3.mirror = true;
		setRotation(this.frontSaw3, 0F, 0F, 0F);
		this.frontSaw4 = new ModelRenderer(this, 48, 2);
		this.frontSaw4.addBox(0F, 0F, 0F, 3, 3, 1);
		this.frontSaw4.setRotationPoint(3F, 13F, -9F);
		this.frontSaw4.setTextureSize(64, 32);
		this.frontSaw4.mirror = true;
		setRotation(this.frontSaw4, 0F, 0F, 0F);
		this.frontSaw5 = new ModelRenderer(this, 56, 2);
		this.frontSaw5.addBox(0F, 0F, 0F, 2, 3, 1);
		this.frontSaw5.setRotationPoint(4F, 16F, -9F);
		this.frontSaw5.setTextureSize(64, 32);
		this.frontSaw5.mirror = true;
		setRotation(this.frontSaw5, 0F, 0F, 0F);
		this.frontSaw6 = new ModelRenderer(this, 48, 6);
		this.frontSaw6.addBox(0F, 0F, 0F, 1, 2, 1);
		this.frontSaw6.setRotationPoint(5F, 19F, -9F);
		this.frontSaw6.setTextureSize(64, 32);
		this.frontSaw6.mirror = true;
		setRotation(this.frontSaw6, 0F, 0F, 0F);
		this.frontHammer1 = new ModelRenderer(this, 48, 9);
		this.frontHammer1.addBox(0F, 0F, 0F, 1, 4, 1);
		this.frontHammer1.setRotationPoint(-5F, 13F, -9F);
		this.frontHammer1.setTextureSize(64, 32);
		this.frontHammer1.mirror = true;
		setRotation(this.frontHammer1, 0F, 0F, 0F);
		this.frontHammer2 = new ModelRenderer(this, 48, 14);
		this.frontHammer2.addBox(0F, 0F, 0F, 2, 1, 1);
		this.frontHammer2.setRotationPoint(-6F, 17F, -9F);
		this.frontHammer2.setTextureSize(64, 32);
		this.frontHammer2.mirror = true;
		setRotation(this.frontHammer2, 0F, 0F, 0F);
		this.frontHammer3 = new ModelRenderer(this, 52, 6);
		this.frontHammer3.addBox(0F, 0F, 0F, 1, 3, 1);
		this.frontHammer3.setRotationPoint(-4F, 16F, -9F);
		this.frontHammer3.setTextureSize(64, 32);
		this.frontHammer3.mirror = true;
		setRotation(this.frontHammer3, 0F, 0F, 0F);
		this.rightSaw1 = new ModelRenderer(this, 56, 6);
		this.rightSaw1.addBox(0F, 0F, 0F, 1, 1, 3);
		this.rightSaw1.setRotationPoint(-9F, 11F, -6F);
		this.rightSaw1.setTextureSize(64, 32);
		this.rightSaw1.mirror = true;
		setRotation(this.rightSaw1, 0F, 0F, 0F);
		this.rightSaw2 = new ModelRenderer(this, 54, 14);
		this.rightSaw2.addBox(0F, 0F, 0F, 1, 1, 1);
		this.rightSaw2.setRotationPoint(-9F, 12F, -6F);
		this.rightSaw2.setTextureSize(64, 32);
		this.rightSaw2.mirror = true;
		setRotation(this.rightSaw2, 0F, 0F, 0F);
		this.rightSaw3 = new ModelRenderer(this, 58, 14);
		this.rightSaw3.addBox(0F, 0F, 0F, 1, 1, 1);
		this.rightSaw3.setRotationPoint(-9F, 12F, -4F);
		this.rightSaw3.setTextureSize(64, 32);
		this.rightSaw3.mirror = true;
		setRotation(this.rightSaw3, 0F, 0F, 0F);
		this.rightSaw4 = new ModelRenderer(this, 0, 10);
		this.rightSaw4.addBox(0F, 0F, 0F, 1, 3, 3);
		this.rightSaw4.setRotationPoint(-9F, 13F, -6F);
		this.rightSaw4.setTextureSize(64, 32);
		this.rightSaw4.mirror = true;
		setRotation(this.rightSaw4, 0F, 0F, 0F);
		this.rightSaw5 = new ModelRenderer(this, 8, 11);
		this.rightSaw5.addBox(0F, 0F, 0F, 1, 3, 2);
		this.rightSaw5.setRotationPoint(-9F, 16F, -6F);
		this.rightSaw5.setTextureSize(64, 32);
		this.rightSaw5.mirror = true;
		setRotation(this.rightSaw5, 0F, 0F, 0F);
		this.rightSaw6 = new ModelRenderer(this, 52, 10);
		this.rightSaw6.addBox(0F, 0F, 0F, 1, 2, 1);
		this.rightSaw6.setRotationPoint(-9F, 19F, -6F);
		this.rightSaw6.setTextureSize(64, 32);
		this.rightSaw6.mirror = true;
		setRotation(this.rightSaw6, 0F, 0F, 0F);
		this.rightHammer1 = new ModelRenderer(this, 8, 6);
		this.rightHammer1.addBox(0F, 0F, 0F, 1, 4, 1);
		this.rightHammer1.setRotationPoint(-9F, 13F, 4F);
		this.rightHammer1.setTextureSize(64, 32);
		this.rightHammer1.mirror = true;
		setRotation(this.rightHammer1, 0F, 0F, 0F);
		this.rightHammer2 = new ModelRenderer(this, 56, 10);
		this.rightHammer2.addBox(0F, 0F, 0F, 1, 1, 2);
		this.rightHammer2.setRotationPoint(-9F, 17F, 4F);
		this.rightHammer2.setTextureSize(64, 32);
		this.rightHammer2.mirror = true;
		setRotation(this.rightHammer2, 0F, 0F, 0F);
		this.rightHammer3 = new ModelRenderer(this, 0, 6);
		this.rightHammer3.addBox(0F, 0F, 0F, 1, 3, 1);
		this.rightHammer3.setRotationPoint(-9F, 16F, 3F);
		this.rightHammer3.setTextureSize(64, 32);
		this.rightHammer3.mirror = true;
		setRotation(this.rightHammer3, 0F, 0F, 0F);
		this.leftCutter1 = new ModelRenderer(this, 4, 7);
		this.leftCutter1.addBox(0F, 0F, 0F, 1, 2, 1);
		this.leftCutter1.setRotationPoint(8F, 13F, -5F);
		this.leftCutter1.setTextureSize(64, 32);
		this.leftCutter1.mirror = true;
		setRotation(this.leftCutter1, 0F, 0F, 0F);
		this.leftCutter2 = new ModelRenderer(this, 4, 5);
		this.leftCutter2.addBox(0F, 0F, 0F, 1, 1, 1);
		this.leftCutter2.setRotationPoint(8F, 15F, -4F);
		this.leftCutter2.setTextureSize(64, 32);
		this.leftCutter2.mirror = true;
		setRotation(this.leftCutter2, 0F, 0F, 0F);
		this.leftCutter3 = new ModelRenderer(this, 12, 8);
		this.leftCutter3.addBox(0F, 0F, 0F, 1, 2, 1);
		this.leftCutter3.setRotationPoint(8F, 13F, -3F);
		this.leftCutter3.setTextureSize(64, 32);
		this.leftCutter3.mirror = true;
		setRotation(this.leftCutter3, 0F, 0F, 0F);
		this.leftCutter4 = new ModelRenderer(this, 12, 5);
		this.leftCutter4.addBox(0F, 0F, 0F, 1, 2, 1);
		this.leftCutter4.setRotationPoint(8F, 16F, -5F);
		this.leftCutter4.setTextureSize(64, 32);
		this.leftCutter4.mirror = true;
		setRotation(this.leftCutter4, 0F, 0F, 0F);
		this.leftCutter5 = new ModelRenderer(this, 8, 3);
		this.leftCutter5.addBox(0F, 0F, 0F, 1, 2, 1);
		this.leftCutter5.setRotationPoint(8F, 16F, -3F);
		this.leftCutter5.setTextureSize(64, 32);
		this.leftCutter5.mirror = true;
		setRotation(this.leftCutter5, 0F, 0F, 0F);
		this.backCutter1 = new ModelRenderer(this, 12, 2);
		this.backCutter1.addBox(0F, 0F, 0F, 1, 2, 1);
		this.backCutter1.setRotationPoint(4F, 13F, 8F);
		this.backCutter1.setTextureSize(64, 32);
		this.backCutter1.mirror = true;
		setRotation(this.backCutter1, 0F, 0F, 0F);
		this.backCutter2 = new ModelRenderer(this, 0, 4);
		this.backCutter2.addBox(0F, 0F, 0F, 1, 1, 1);
		this.backCutter2.setRotationPoint(3F, 15F, 8F);
		this.backCutter2.setTextureSize(64, 32);
		this.backCutter2.mirror = true;
		setRotation(this.backCutter2, 0F, 0F, 0F);
		this.backCutter3 = new ModelRenderer(this, 4, 2);
		this.backCutter3.addBox(0F, 0F, 0F, 1, 2, 1);
		this.backCutter3.setRotationPoint(2F, 13F, 8F);
		this.backCutter3.setTextureSize(64, 32);
		this.backCutter3.mirror = true;
		setRotation(this.backCutter3, 0F, 0F, 0F);
		this.backCutter4 = new ModelRenderer(this, 8, 0);
		this.backCutter4.addBox(0F, 0F, 0F, 1, 2, 1);
		this.backCutter4.setRotationPoint(4F, 16F, 8F);
		this.backCutter4.setTextureSize(64, 32);
		this.backCutter4.mirror = true;
		setRotation(this.backCutter4, 0F, 0F, 0F);
		this.backCutter5 = new ModelRenderer(this, 0, 1);
		this.backCutter5.addBox(0F, 0F, 0F, 1, 2, 1);
		this.backCutter5.setRotationPoint(2F, 16F, 8F);
		this.backCutter5.setTextureSize(64, 32);
		this.backCutter5.mirror = true;
		setRotation(this.backCutter5, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		this.base.render(f5);
		this.frontSaw1.render(f5);
		this.frontSaw2.render(f5);
		this.frontSaw3.render(f5);
		this.frontSaw4.render(f5);
		this.frontSaw5.render(f5);
		this.frontSaw6.render(f5);
		this.frontHammer1.render(f5);
		this.frontHammer2.render(f5);
		this.frontHammer3.render(f5);
		this.rightSaw1.render(f5);
		this.rightSaw2.render(f5);
		this.rightSaw3.render(f5);
		this.rightSaw4.render(f5);
		this.rightSaw5.render(f5);
		this.rightSaw6.render(f5);
		this.rightHammer1.render(f5);
		this.rightHammer2.render(f5);
		this.rightHammer3.render(f5);
		this.leftCutter1.render(f5);
		this.leftCutter2.render(f5);
		this.leftCutter3.render(f5);
		this.leftCutter4.render(f5);
		this.leftCutter5.render(f5);
		this.backCutter1.render(f5);
		this.backCutter2.render(f5);
		this.backCutter3.render(f5);
		this.backCutter4.render(f5);
		this.backCutter5.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
