// Date: 10/8/2014 10:29:38 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelarcane_forge extends ModelBase
{
  //fields
    ModelRenderer Pillar1;
    ModelRenderer Pillar2;
    ModelRenderer Pillar3;
    ModelRenderer Pillar4;
    ModelRenderer Pillar5;
    ModelRenderer Pillar6;
    ModelRenderer Pillar7;
    ModelRenderer Pillar8;
    ModelRenderer Gem1;
    ModelRenderer Gem2;
    ModelRenderer Gem3;
    ModelRenderer Gem4;
    ModelRenderer Gem5;
    ModelRenderer Gem6;
    ModelRenderer Gem7;
    ModelRenderer Gem8;
    ModelRenderer Base;
  
  public Modelarcane_forge()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Pillar1 = new ModelRenderer(this, 0, 0);
      Pillar1.addBox(0F, 0F, 0F, 2, 11, 2);
      Pillar1.setRotationPoint(-8F, 13F, 6F);
      Pillar1.setTextureSize(64, 32);
      Pillar1.mirror = true;
      setRotation(Pillar1, 0F, 0F, 0F);
      Pillar2 = new ModelRenderer(this, 0, 0);
      Pillar2.addBox(0F, 0F, 0F, 2, 11, 2);
      Pillar2.setRotationPoint(6F, 13F, 6F);
      Pillar2.setTextureSize(64, 32);
      Pillar2.mirror = true;
      setRotation(Pillar2, 0F, 0F, 0F);
      Pillar3 = new ModelRenderer(this, 0, 0);
      Pillar3.addBox(0F, 0F, 0F, 2, 11, 2);
      Pillar3.setRotationPoint(6F, 13F, -8F);
      Pillar3.setTextureSize(64, 32);
      Pillar3.mirror = true;
      setRotation(Pillar3, 0F, 0F, 0F);
      Pillar4 = new ModelRenderer(this, 0, 0);
      Pillar4.addBox(0F, 0F, 0F, 2, 11, 2);
      Pillar4.setRotationPoint(-8F, 13F, -8F);
      Pillar4.setTextureSize(64, 32);
      Pillar4.mirror = true;
      setRotation(Pillar4, 0F, 0F, 0F);
      Pillar5 = new ModelRenderer(this, 0, 0);
      Pillar5.addBox(0F, 0F, 0F, 2, 11, 2);
      Pillar5.setRotationPoint(6F, 13F, -1F);
      Pillar5.setTextureSize(64, 32);
      Pillar5.mirror = true;
      setRotation(Pillar5, 0F, 0F, 0F);
      Pillar6 = new ModelRenderer(this, 0, 0);
      Pillar6.addBox(0F, 0F, 0F, 2, 11, 2);
      Pillar6.setRotationPoint(-1F, 13F, -8F);
      Pillar6.setTextureSize(64, 32);
      Pillar6.mirror = true;
      setRotation(Pillar6, 0F, 0F, 0F);
      Pillar7 = new ModelRenderer(this, 0, 0);
      Pillar7.addBox(0F, 0F, 0F, 2, 11, 2);
      Pillar7.setRotationPoint(-8F, 13F, -1F);
      Pillar7.setTextureSize(64, 32);
      Pillar7.mirror = true;
      setRotation(Pillar7, 0F, 0F, 0F);
      Pillar8 = new ModelRenderer(this, 0, 0);
      Pillar8.addBox(0F, 0F, 0F, 2, 11, 2);
      Pillar8.setRotationPoint(-1F, 13F, 6F);
      Pillar8.setTextureSize(64, 32);
      Pillar8.mirror = true;
      setRotation(Pillar8, 0F, 0F, 0F);
      Gem1 = new ModelRenderer(this, 42, 0);
      Gem1.addBox(0F, 0F, -2F, 2, 2, 2);
      Gem1.setRotationPoint(-7F, 9F, 7F);
      Gem1.setTextureSize(64, 32);
      Gem1.mirror = true;
      setRotation(Gem1, 0.7853982F, 0.7853982F, 0.7853982F);
      Gem2 = new ModelRenderer(this, 42, 4);
      Gem2.addBox(0F, 0F, -2F, 2, 2, 2);
      Gem2.setRotationPoint(7F, 9F, 7F);
      Gem2.setTextureSize(64, 32);
      Gem2.mirror = true;
      setRotation(Gem2, 0.7853982F, 0.7853982F, 0.7853982F);
      Gem3 = new ModelRenderer(this, 42, 8);
      Gem3.addBox(0F, 0F, -2F, 2, 2, 2);
      Gem3.setRotationPoint(7F, 9F, -7F);
      Gem3.setTextureSize(64, 32);
      Gem3.mirror = true;
      setRotation(Gem3, 0.7853982F, 0.7853982F, 0.7853982F);
      Gem4 = new ModelRenderer(this, 50, 0);
      Gem4.addBox(0F, 0F, -2F, 2, 2, 2);
      Gem4.setRotationPoint(-7F, 9F, -7F);
      Gem4.setTextureSize(64, 32);
      Gem4.mirror = true;
      setRotation(Gem4, 0.7853982F, 0.7853982F, 0.7853982F);
      Gem5 = new ModelRenderer(this, 50, 4);
      Gem5.addBox(0F, 0F, -2F, 2, 2, 2);
      Gem5.setRotationPoint(7F, 9F, 0F);
      Gem5.setTextureSize(64, 32);
      Gem5.mirror = true;
      setRotation(Gem5, 0.7853982F, 0.7853982F, 0.7853982F);
      Gem6 = new ModelRenderer(this, 50, 8);
      Gem6.addBox(0F, 0F, -2F, 2, 2, 2);
      Gem6.setRotationPoint(0F, 9F, -7F);
      Gem6.setTextureSize(64, 32);
      Gem6.mirror = true;
      setRotation(Gem6, 0.7853982F, 0.7853982F, 0.7853982F);
      Gem7 = new ModelRenderer(this, 0, 24);
      Gem7.addBox(0F, 0F, -2F, 2, 2, 2);
      Gem7.setRotationPoint(-7F, 9F, 0F);
      Gem7.setTextureSize(64, 32);
      Gem7.mirror = true;
      setRotation(Gem7, 0.7853982F, 0.7853982F, 0.7853982F);
      Gem8 = new ModelRenderer(this, 8, 24);
      Gem8.addBox(0F, 0F, -2F, 2, 2, 2);
      Gem8.setRotationPoint(0F, 9F, 7F);
      Gem8.setTextureSize(64, 32);
      Gem8.mirror = true;
      setRotation(Gem8, 0.7853982F, 0.7853982F, 0.7853982F);
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 14, 10, 14);
      Base.setRotationPoint(-7F, 14F, -7F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Pillar1.render(f5);
    Pillar2.render(f5);
    Pillar3.render(f5);
    Pillar4.render(f5);
    Pillar5.render(f5);
    Pillar6.render(f5);
    Pillar7.render(f5);
    Pillar8.render(f5);
    Gem1.render(f5);
    Gem2.render(f5);
    Gem3.render(f5);
    Gem4.render(f5);
    Gem5.render(f5);
    Gem6.render(f5);
    Gem7.render(f5);
    Gem8.render(f5);
    Base.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
