// Date: 11/26/2013 11:17:38 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package sobiohazardous.minestrappolation.extradecor.tileentity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlate extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer PlateA;
    ModelRenderer PlateB;
    ModelRenderer PlateC;
    ModelRenderer PlateD;
    ModelRenderer PlateE;
    ModelRenderer PlateF;
    ModelRenderer PlateG;
    ModelRenderer PlateH;
    ModelRenderer PlateI;
  
  public ModelPlate()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 8, 1, 8);
      Base.setRotationPoint(-4F, 23F, -4F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      PlateA = new ModelRenderer(this, 0, 9);
      PlateA.addBox(0F, 0F, 0F, 16, 1, 6);
      PlateA.setRotationPoint(-8F, 22F, -3F);
      PlateA.setTextureSize(64, 32);
      PlateA.mirror = true;
      setRotation(PlateA, 0F, 0F, 0F);
      PlateB = new ModelRenderer(this, 0, 16);
      PlateB.addBox(0F, 0F, 0F, 14, 1, 2);
      PlateB.setRotationPoint(-7F, 22F, 3F);
      PlateB.setTextureSize(64, 32);
      PlateB.mirror = true;
      setRotation(PlateB, 0F, 0F, 0F);
      PlateC = new ModelRenderer(this, 0, 19);
      PlateC.addBox(0F, 0F, 0F, 14, 1, 2);
      PlateC.setRotationPoint(-7F, 22F, -5F);
      PlateC.setTextureSize(64, 32);
      PlateC.mirror = true;
      setRotation(PlateC, 0F, 0F, 0F);
      PlateD = new ModelRenderer(this, 0, 22);
      PlateD.addBox(0F, 0F, 0F, 12, 1, 1);
      PlateD.setRotationPoint(-6F, 22F, 5F);
      PlateD.setTextureSize(64, 32);
      PlateD.mirror = true;
      setRotation(PlateD, 0F, 0F, 0F);
      PlateE = new ModelRenderer(this, 0, 24);
      PlateE.addBox(0F, 0F, 0F, 12, 1, 1);
      PlateE.setRotationPoint(-6F, 22F, -6F);
      PlateE.setTextureSize(64, 32);
      PlateE.mirror = true;
      setRotation(PlateE, 0F, 0F, 0F);
      PlateF = new ModelRenderer(this, 0, 26);
      PlateF.addBox(0F, 0F, 0F, 10, 1, 1);
      PlateF.setRotationPoint(-5F, 22F, 6F);
      PlateF.setTextureSize(64, 32);
      PlateF.mirror = true;
      setRotation(PlateF, 0F, 0F, 0F);
      PlateG = new ModelRenderer(this, 0, 28);
      PlateG.addBox(0F, 0F, 0F, 10, 1, 1);
      PlateG.setRotationPoint(-5F, 22F, -7F);
      PlateG.setTextureSize(64, 32);
      PlateG.mirror = true;
      setRotation(PlateG, 0F, 0F, 0F);
      PlateH = new ModelRenderer(this, 32, 0);
      PlateH.addBox(0F, 0F, 0F, 6, 1, 1);
      PlateH.setRotationPoint(-3F, 22F, 7F);
      PlateH.setTextureSize(64, 32);
      PlateH.mirror = true;
      setRotation(PlateH, 0F, 0F, 0F);
      PlateI = new ModelRenderer(this, 32, 2);
      PlateI.addBox(0F, 0F, 0F, 6, 1, 1);
      PlateI.setRotationPoint(-3F, 22F, -8F);
      PlateI.setTextureSize(64, 32);
      PlateI.mirror = true;
      setRotation(PlateI, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    Base.render(f5);
    PlateA.render(f5);
    PlateB.render(f5);
    PlateC.render(f5);
    PlateD.render(f5);
    PlateE.render(f5);
    PlateF.render(f5);
    PlateG.render(f5);
    PlateH.render(f5);
    PlateI.render(f5);
  }
  
  public void render(float f5){
	  Base.render(f5);
	    PlateA.render(f5);
	    PlateB.render(f5);
	    PlateC.render(f5);
	    PlateD.render(f5);
	    PlateE.render(f5);
	    PlateF.render(f5);
	    PlateG.render(f5);
	    PlateH.render(f5);
	    PlateI.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
